# SwiftLint Configuration for J2KSwift

# Paths to include for linting
included:
  - Sources
  - Tests

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Packages
  - DerivedData

# Enabled rules
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_comma
  - force_try

# Rule configurations

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 2000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 150

function_parameter_count:
  warning: 5
  error: 10

type_body_length:
  warning: 300
  error: 2000

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - T
    - U
    - V

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  allowed_symbols:
    - _
  excluded:
    - id
    - x
    - y
    - z
    - r
    - g
    - b
    - a
    - dx
    - dy
    - i
    - j
    - k
    - C1
    - C2
    - n
    - c
    - h
    - v
    - d
    - m
    - l
    - s
    - w
    - q
    - p
    - f
    - u
    - t
    - K
    - e

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 5
    error: 10

cyclomatic_complexity:
  warning: 10
  error: 30
  ignores_case_statements: true

large_tuple:
  warning: 3
  error: 5

# File header configuration
file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*?\.swift
                    \/\/ J2KSwift
                    \/\/

# Custom rules
custom_rules:
  # Discourage force unwrapping in production code
  force_unwrap_in_sources:
    name: "Force Unwrap"
    regex: "\\!(?!\\s*\\/\\/)"
    match_kinds:
      - identifier
    included: "Sources/.*\\.swift"
    message: "Avoid force unwrapping in production code. Use proper error handling."
    severity: warning
  
  # Ensure proper documentation for public APIs
  missing_docs:
    name: "Missing Documentation"
    regex: "^\\s*(public|open)\\s+(func|var|let|class|struct|enum|protocol|typealias|actor)"
    match_kinds: keyword
    message: "Public declarations should have documentation comments"
    severity: warning

# Reporter type
reporter: "xcode"
