// V94NEONHotPathParityTests.swift
//
// v9.4-research — bit-exact parity gates for the custom C+NEON tier-1
// HT block encoder. These tests are the SOLE acceptance criterion for
// the C+NEON hot path: any timing measurement is meaningful only if
// every parity sweep here passes.
//
// Day 2a scope (this commit): table-identity gates.
//   - testDumpTablesToC: helper that prints the Swift conformant
//     table values as C array-initialiser source. Used once at table
//     transcription time; output is hand-pasted into
//     Sources/J2KCodecNEON/j2knhe_tables.c.
//   - testTablesMatchSwiftSourceOfTruth: continuous bit-identity
//     gate. Asserts the C arrays exposed via J2KCodecNEON match the
//     Swift `vlcTable0Conformant` / `vlcTable1Conformant` /
//     `uvlcTableConformant` arrays element-by-element. Runs on every
//     CI build to guard against table drift.
//
// Day 2b/2c scope (follow-up commits): per-block byte-equality gates
//   - testAllZeroBlock_64x64
//   - testSingleSignificantSample_64x64
//   - testSparseSignificance_5pct_64x64
//   - testDenseSignificance_30pct_64x64
//   - testNonPow2 dimensions (3x5, 47x39, 63x63, 1x64, 64x1)
//   - testMissingMSBsSweep (p = 1, 5, 10, 15, 20, 25, 28, 29)
//   - testRandomSweep_500trials (sparse-to-dense × p-sweep)
// Each: encode via Swift path AND C+NEON path; assert byte-exact
// equality on (magsgn, mel, vlc).

import XCTest
@testable import J2KCodec
import J2KCodecNEON

final class V94NEONHotPathParityTests: XCTestCase {

    /// Run-once helper: emits a C source body for j2knhe_tables.c that
    /// reflects the current Swift lazily-initialized table contents.
    /// Output goes to stdout; the human paste-target is
    /// Sources/J2KCodecNEON/j2knhe_tables.c.
    ///
    /// Re-run only when the Swift tables change (rare — they encode
    /// JPEG 2000 Part-15 standard constants from ITU-T T.814).
    func testDumpTablesToC() throws {
        // Code-generation helper, not an assertion. Run explicitly:
        //   swift test --filter V94NEONHotPathParityTests/testDumpTablesToC
        // The C-source body is printed to stdout; pipe to a file and
        // paste into Sources/J2KCodecNEON/j2knhe_tables.c.
        // Smoke check first: tables exist and have expected sizes.
        XCTAssertEqual(vlcTable0Conformant.count, 2048)
        XCTAssertEqual(vlcTable1Conformant.count, 2048)
        XCTAssertEqual(uvlcTableConformant.count, 75)

        var output = ""
        output += "// j2knhe_tables.c — generated by V94NEONHotPathParityTests.testDumpTablesToC()\n"
        output += "// DO NOT EDIT BY HAND. Re-run the dump test if the Swift tables change.\n"
        output += "// Values are JPEG 2000 Part-15 mathematical constants (ITU-T T.814);\n"
        output += "// transcribed from our Swift source-of-truth in J2KHTConformantTables.swift.\n\n"
        output += "#include \"j2knhe_tables.h\"\n\n"

        output += dumpUInt16Array(name: "j2knhe_vlc_table0",
                                  values: vlcTable0Conformant)
        output += "\n"
        output += dumpUInt16Array(name: "j2knhe_vlc_table1",
                                  values: vlcTable1Conformant)
        output += "\n"
        output += dumpUVLCArray(name: "j2knhe_uvlc_table",
                                values: uvlcTableConformant)

        print("\n========== BEGIN j2knhe_tables.c ==========")
        print(output)
        print("========== END j2knhe_tables.c ==========\n")
    }

    /// Continuous gate: assert the C tables match the Swift tables
    /// element-by-element. Runs in CI on every build. If this fails,
    /// the C+NEON encoder will produce divergent codestreams and must
    /// not be enabled in production.
    func testTablesMatchSwiftSourceOfTruth() throws {
        // VLC table 0: 2048 entries × UInt16
        for i in 0..<2048 {
            let cValue = withUnsafePointer(to: j2knhe_vlc_table0) { ptr in
                ptr.withMemoryRebound(to: UInt16.self, capacity: 2048) { p in
                    p[i]
                }
            }
            let swiftValue = vlcTable0Conformant[i]
            XCTAssertEqual(cValue, swiftValue,
                "vlcTable0 entry \(i) divergence: C=\(cValue) Swift=\(swiftValue)")
        }
        // VLC table 1: 2048 entries × UInt16
        for i in 0..<2048 {
            let cValue = withUnsafePointer(to: j2knhe_vlc_table1) { ptr in
                ptr.withMemoryRebound(to: UInt16.self, capacity: 2048) { p in
                    p[i]
                }
            }
            let swiftValue = vlcTable1Conformant[i]
            XCTAssertEqual(cValue, swiftValue,
                "vlcTable1 entry \(i) divergence: C=\(cValue) Swift=\(swiftValue)")
        }
        // UVLC table: 75 entries × packed UInt32
        // Swift representation is UVLCEntry struct; C is a uint32_t
        // bit-packed as (preLen << 16 | pre) | (sufLen << 24 | suf << 8)
        // Per j2knhe_tables.h doc: bits 0..7 = pre, 8..15 = preLen,
        //                          16..23 = suf, 24..31 = sufLen.
        // Verify the packing matches what j2knhe_encode_block_ht.c expects.
        for i in 0..<75 {
            let entry = uvlcTableConformant[i]
            let cValue = withUnsafePointer(to: j2knhe_uvlc_table) { ptr in
                ptr.withMemoryRebound(to: UInt32.self, capacity: 75) { p in
                    p[i]
                }
            }
            let expected: UInt32 =
                UInt32(entry.pre & 0xFF)
                | (UInt32(entry.preLen & 0xFF) << 8)
                | (UInt32(entry.suf & 0xFF)    << 16)
                | (UInt32(entry.sufLen & 0xFF) << 24)
            XCTAssertEqual(cValue, expected,
                "uvlcTable entry \(i) divergence: C=\(cValue) expected=\(expected)")
        }
    }

    // MARK: - Block-level parity (Day 2b — scalar C vs Swift)

    /// Encode `coefficients` (width × height row-major UInt32 sign-mag)
    /// via BOTH the Swift v9.3 path and the C scalar path. Assert
    /// byte-exact equality on (magsgn, mel, vlc).
    private func assertBitExactParity(
        _ coefficients: [UInt32],
        width: Int, height: Int, missingMSBs: Int,
        label: String, file: StaticString = #file, line: UInt = #line
    ) {
        // Swift v9.3 path
        var swMag = HTMagSgnEncoderConformant()
        var swMel = HTMELEncoderConformant()
        var swVlc = HTReverseBitEmitterConformant()
        let swResult = coefficients.withUnsafeBufferPointer { ptr in
            HTBlockEncoderConformant.encode(
                coefficients: ptr,
                width: width, height: height,
                missingMSBs: missingMSBs,
                magsgnEnc: &swMag, melEnc: &swMel, vlcEnc: &swVlc,
                useSIMDClassification: false,
                preClassifiedTuples: nil)
        }
        // C scalar path
        var cMagBuf = [UInt8](repeating: 0, count: 16384)
        var cMelBuf = [UInt8](repeating: 0, count: 4096)
        var cVlcBuf = [UInt8](repeating: 0, count: 4096)
        var cMagLen: Int = 0
        var cMelLen: Int = 0
        var cVlcLen: Int = 0
        let rc = coefficients.withUnsafeBufferPointer { coefPtr in
            cMagBuf.withUnsafeMutableBufferPointer { magPtr in
                cMelBuf.withUnsafeMutableBufferPointer { melPtr in
                    cVlcBuf.withUnsafeMutableBufferPointer { vlcPtr in
                        j2knhe_encode_block_ht32(
                            coefPtr.baseAddress!,
                            UInt32(width), UInt32(height),
                            UInt32(missingMSBs),
                            magPtr.baseAddress!, magPtr.count, &cMagLen,
                            melPtr.baseAddress!, melPtr.count, &cMelLen,
                            vlcPtr.baseAddress!, vlcPtr.count, &cVlcLen)
                    }
                }
            }
        }
        XCTAssertEqual(rc, 0, "\(label): C encoder returned non-zero",
                       file: file, line: line)
        XCTAssertEqual(cMagLen, swResult.magsgn.count,
                       "\(label): magsgn length mismatch (sw=\(swResult.magsgn.count) c=\(cMagLen))",
                       file: file, line: line)
        XCTAssertEqual(Array(cMagBuf[0..<cMagLen]), swResult.magsgn,
                       "\(label): magsgn bytes differ",
                       file: file, line: line)
        XCTAssertEqual(cMelLen, swResult.mel.count,
                       "\(label): mel length mismatch (sw=\(swResult.mel.count) c=\(cMelLen))",
                       file: file, line: line)
        XCTAssertEqual(Array(cMelBuf[0..<cMelLen]), swResult.mel,
                       "\(label): mel bytes differ",
                       file: file, line: line)
        XCTAssertEqual(cVlcLen, swResult.vlc.count,
                       "\(label): vlc length mismatch (sw=\(swResult.vlc.count) c=\(cVlcLen))",
                       file: file, line: line)
        XCTAssertEqual(Array(cVlcBuf[0..<cVlcLen]), swResult.vlc,
                       "\(label): vlc bytes differ",
                       file: file, line: line)
    }

    func testAllZeroBlock_64x64() throws {
        let coefficients = [UInt32](repeating: 0, count: 64 * 64)
        assertBitExactParity(coefficients, width: 64, height: 64,
                             missingMSBs: 24, label: "AllZero64x64")
    }

    func testSingleSignificantSample_64x64() throws {
        var block = [UInt32](repeating: 0, count: 64 * 64)
        block[0] = 0x0000_0040  // magnitude 64, p=6
        assertBitExactParity(block, width: 64, height: 64,
                             missingMSBs: 24, label: "SingleSig64x64")
    }

    func testSingleSignificantSample_MidRow_64x64() throws {
        var block = [UInt32](repeating: 0, count: 64 * 64)
        block[32 * 64 + 16] = 0x8000_0080
        assertBitExactParity(block, width: 64, height: 64,
                             missingMSBs: 24, label: "MidRowSig64x64")
    }

    func testSparseSignificance_5pct_64x64() throws {
        var block = [UInt32](repeating: 0, count: 64 * 64)
        // 200 significant samples out of 4096 (~5%), stride pattern
        let stride = (64 * 64) / 200
        for i in 0..<200 {
            let idx = i * stride
            if idx < block.count {
                block[idx] = (i & 1 == 0) ? 0x0000_0080 : 0x8000_0080
            }
        }
        assertBitExactParity(block, width: 64, height: 64,
                             missingMSBs: 24, label: "Sparse5pct64x64")
    }

    func testDenseSignificance_30pct_64x64() throws {
        var block = [UInt32](repeating: 0, count: 64 * 64)
        // ~30% significant, varied magnitudes. Use `truncatingIfNeeded`
        // for the UInt64 → UInt32 cast since random `z` can exceed
        // UInt32.max and the default initializer traps on overflow.
        var seed: UInt64 = 0x9E37_79B9_7F4A_7C15
        for i in 0..<block.count {
            seed &+= 0x9E37_79B9_7F4A_7C15
            var z = seed
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            z ^= (z >> 31)
            if (z & 0xFF) < 76 {
                let mag = UInt32(truncatingIfNeeded: z >> 8) & 0x003F
                let sign: UInt32 = (z & 0x8000) != 0 ? 0x8000_0000 : 0
                block[i] = sign | mag
            }
        }
        assertBitExactParity(block, width: 64, height: 64,
                             missingMSBs: 24, label: "Dense30pct64x64")
    }

    func testNonPow2_3x5() throws {
        let block: [UInt32] = [
            0x0000_0010, 0, 0x8000_0008,
            0,           0x0000_0004, 0,
            0x8000_0020, 0, 0,
            0x0000_0001, 0x8000_0002, 0,
            0,           0, 0x0000_0040,
        ]
        assertBitExactParity(block, width: 3, height: 5,
                             missingMSBs: 24, label: "NonPow2 3x5")
    }

    func testNonPow2_47x39() throws {
        var block = [UInt32](repeating: 0, count: 47 * 39)
        // Significance pattern shaped to exercise edge-of-row boundary
        // handling and odd quad-pair tail behaviour.
        var seed: UInt64 = 0xBEEF_CAFE_FEED_FACE
        for i in 0..<block.count {
            seed &+= 0x9E37_79B9_7F4A_7C15
            var z = seed
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z ^= (z >> 27)
            if (z & 0xFF) < 38 {
                block[i] = UInt32(truncatingIfNeeded: z & 0x80FF)
            }
        }
        assertBitExactParity(block, width: 47, height: 39,
                             missingMSBs: 24, label: "NonPow2 47x39")
    }

    func testMissingMSBsSweep_64x64() throws {
        // p = 30 - missing_msbs. We sweep missing_msbs across
        // {24, 20, 15, 10, 5, 1} corresponding to p ∈ {6, 10, 15, 20, 25, 29}.
        for missing in [24, 20, 15, 10, 5, 1] {
            var block = [UInt32](repeating: 0, count: 64 * 64)
            let p = 30 - missing
            // Generate samples with magnitudes that just exceed the
            // significance threshold for this p.
            var seed: UInt64 = UInt64(0xDEADBEEF) &+ UInt64(missing) &* 1000
            for i in 0..<block.count {
                seed &+= 0x9E37_79B9_7F4A_7C15
                var z = seed
                z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
                z ^= (z >> 31)
                if (z & 0xFF) < 76 {
                    // magnitude bits go in [0, 30-p) range
                    let magWidth = 30 - p + 4
                    let mag = UInt32(truncatingIfNeeded: z >> 8) & ((UInt32(1) << magWidth) - 1)
                    let sign: UInt32 = (z & 0x8000) != 0 ? 0x8000_0000 : 0
                    block[i] = sign | mag
                }
            }
            assertBitExactParity(block, width: 64, height: 64,
                                 missingMSBs: missing,
                                 label: "MissingMSBs=\(missing)")
        }
    }

    func testRandomSweep_500trials() throws {
        // Day 3 — 500-trial random sweep across width/height/density/
        // missing-MSBs space. Mirrors the V91Phase2cArrayVsRawParityTests
        // 200-trial sweep + 250 additional trials in the v9.4 ranges.
        var seed: UInt64 = 0xCAFEBABE_DEADBEEF
        for trial in 0..<500 {
            seed &+= 0x9E37_79B9_7F4A_7C15
            let w = 16 + Int((seed >> 8) % 49)   // [16, 64]
            let h = 16 + Int((seed >> 16) % 49)  // [16, 64]
            let missing = 5 + Int((seed >> 24) % 24)  // [5, 28]
            let density = Int((seed >> 32) % 128)  // [0, 127]
            var block = [UInt32](repeating: 0, count: w * h)
            var s = seed
            for i in 0..<block.count {
                s &+= 0x9E37_79B9_7F4A_7C15
                var z = s
                z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
                z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
                z ^= (z >> 31)
                if (z & 0xFF) < UInt64(density) {
                    let magWidth = 30 - (30 - missing) + 4
                    let cap = (magWidth >= 31) ? UInt32(0x7FFF_FFFF)
                                               : ((UInt32(1) << magWidth) - 1)
                    let mag = UInt32(truncatingIfNeeded: z >> 8) & cap
                    let sign: UInt32 = (z & 0x8000) != 0 ? 0x8000_0000 : 0
                    block[i] = sign | mag
                }
            }
            assertBitExactParity(block, width: w, height: h,
                                 missingMSBs: missing,
                                 label: "Random trial \(trial) [\(w)x\(h) m=\(missing) d=\(density)]")
        }
    }

    // MARK: - C dump helpers (Day 2a only; deleted once tables stable)

    private func dumpUInt16Array(name: String, values: [UInt16]) -> String {
        var s = "const uint16_t \(name)[2048] = {\n"
        let perLine = 8
        for row in stride(from: 0, to: values.count, by: perLine) {
            s += "    "
            let end = min(row + perLine, values.count)
            for i in row..<end {
                s += String(format: "0x%04X,", values[i])
                if i < end - 1 { s += " " }
            }
            s += "\n"
        }
        s += "};\n"
        return s
    }

    private func dumpUVLCArray(name: String, values: [UVLCEntry]) -> String {
        var s = "const uint32_t \(name)[\(values.count)] = {\n"
        for (i, e) in values.enumerated() {
            let packed: UInt32 =
                UInt32(e.pre & 0xFF)
                | (UInt32(e.preLen & 0xFF) << 8)
                | (UInt32(e.suf & 0xFF)    << 16)
                | (UInt32(e.sufLen & 0xFF) << 24)
            s += String(format: "    0x%08X, // [%2d] pre=%d preLen=%d suf=%d sufLen=%d\n",
                        packed, i, e.pre, e.preLen, e.suf, e.sufLen)
        }
        s += "};\n"
        return s
    }
}
