// V94NEONHotPathParityTests.swift
//
// v9.4-research — bit-exact parity gates for the custom C+NEON tier-1
// HT block encoder. These tests are the SOLE acceptance criterion for
// the C+NEON hot path: any timing measurement is meaningful only if
// every parity sweep here passes.
//
// Day 2a scope (this commit): table-identity gates.
//   - testDumpTablesToC: helper that prints the Swift conformant
//     table values as C array-initialiser source. Used once at table
//     transcription time; output is hand-pasted into
//     Sources/J2KCodecNEON/j2knhe_tables.c.
//   - testTablesMatchSwiftSourceOfTruth: continuous bit-identity
//     gate. Asserts the C arrays exposed via J2KCodecNEON match the
//     Swift `vlcTable0Conformant` / `vlcTable1Conformant` /
//     `uvlcTableConformant` arrays element-by-element. Runs on every
//     CI build to guard against table drift.
//
// Day 2b/2c scope (follow-up commits): per-block byte-equality gates
//   - testAllZeroBlock_64x64
//   - testSingleSignificantSample_64x64
//   - testSparseSignificance_5pct_64x64
//   - testDenseSignificance_30pct_64x64
//   - testNonPow2 dimensions (3x5, 47x39, 63x63, 1x64, 64x1)
//   - testMissingMSBsSweep (p = 1, 5, 10, 15, 20, 25, 28, 29)
//   - testRandomSweep_500trials (sparse-to-dense × p-sweep)
// Each: encode via Swift path AND C+NEON path; assert byte-exact
// equality on (magsgn, mel, vlc).

import XCTest
@testable import J2KCodec
import J2KCodecNEON

final class V94NEONHotPathParityTests: XCTestCase {

    /// Run-once helper: emits a C source body for j2knhe_tables.c that
    /// reflects the current Swift lazily-initialized table contents.
    /// Output goes to stdout; the human paste-target is
    /// Sources/J2KCodecNEON/j2knhe_tables.c.
    ///
    /// Re-run only when the Swift tables change (rare — they encode
    /// JPEG 2000 Part-15 standard constants from ITU-T T.814).
    func testDumpTablesToC() throws {
        // Code-generation helper, not an assertion. Run explicitly:
        //   swift test --filter V94NEONHotPathParityTests/testDumpTablesToC
        // The C-source body is printed to stdout; pipe to a file and
        // paste into Sources/J2KCodecNEON/j2knhe_tables.c.
        // Smoke check first: tables exist and have expected sizes.
        XCTAssertEqual(vlcTable0Conformant.count, 2048)
        XCTAssertEqual(vlcTable1Conformant.count, 2048)
        XCTAssertEqual(uvlcTableConformant.count, 75)

        var output = ""
        output += "// j2knhe_tables.c — generated by V94NEONHotPathParityTests.testDumpTablesToC()\n"
        output += "// DO NOT EDIT BY HAND. Re-run the dump test if the Swift tables change.\n"
        output += "// Values are JPEG 2000 Part-15 mathematical constants (ITU-T T.814);\n"
        output += "// transcribed from our Swift source-of-truth in J2KHTConformantTables.swift.\n\n"
        output += "#include \"j2knhe_tables.h\"\n\n"

        output += dumpUInt16Array(name: "j2knhe_vlc_table0",
                                  values: vlcTable0Conformant)
        output += "\n"
        output += dumpUInt16Array(name: "j2knhe_vlc_table1",
                                  values: vlcTable1Conformant)
        output += "\n"
        output += dumpUVLCArray(name: "j2knhe_uvlc_table",
                                values: uvlcTableConformant)

        print("\n========== BEGIN j2knhe_tables.c ==========")
        print(output)
        print("========== END j2knhe_tables.c ==========\n")
    }

    /// Continuous gate: assert the C tables match the Swift tables
    /// element-by-element. Runs in CI on every build. If this fails,
    /// the C+NEON encoder will produce divergent codestreams and must
    /// not be enabled in production.
    func testTablesMatchSwiftSourceOfTruth() throws {
        // VLC table 0: 2048 entries × UInt16
        for i in 0..<2048 {
            let cValue = withUnsafePointer(to: j2knhe_vlc_table0) { ptr in
                ptr.withMemoryRebound(to: UInt16.self, capacity: 2048) { p in
                    p[i]
                }
            }
            let swiftValue = vlcTable0Conformant[i]
            XCTAssertEqual(cValue, swiftValue,
                "vlcTable0 entry \(i) divergence: C=\(cValue) Swift=\(swiftValue)")
        }
        // VLC table 1: 2048 entries × UInt16
        for i in 0..<2048 {
            let cValue = withUnsafePointer(to: j2knhe_vlc_table1) { ptr in
                ptr.withMemoryRebound(to: UInt16.self, capacity: 2048) { p in
                    p[i]
                }
            }
            let swiftValue = vlcTable1Conformant[i]
            XCTAssertEqual(cValue, swiftValue,
                "vlcTable1 entry \(i) divergence: C=\(cValue) Swift=\(swiftValue)")
        }
        // UVLC table: 75 entries × packed UInt32
        // Swift representation is UVLCEntry struct; C is a uint32_t
        // bit-packed as (preLen << 16 | pre) | (sufLen << 24 | suf << 8)
        // Per j2knhe_tables.h doc: bits 0..7 = pre, 8..15 = preLen,
        //                          16..23 = suf, 24..31 = sufLen.
        // Verify the packing matches what j2knhe_encode_block_ht.c expects.
        for i in 0..<75 {
            let entry = uvlcTableConformant[i]
            let cValue = withUnsafePointer(to: j2knhe_uvlc_table) { ptr in
                ptr.withMemoryRebound(to: UInt32.self, capacity: 75) { p in
                    p[i]
                }
            }
            let expected: UInt32 =
                UInt32(entry.pre & 0xFF)
                | (UInt32(entry.preLen & 0xFF) << 8)
                | (UInt32(entry.suf & 0xFF)    << 16)
                | (UInt32(entry.sufLen & 0xFF) << 24)
            XCTAssertEqual(cValue, expected,
                "uvlcTable entry \(i) divergence: C=\(cValue) expected=\(expected)")
        }
    }

    // MARK: - C dump helpers (Day 2a only; deleted once tables stable)

    private func dumpUInt16Array(name: String, values: [UInt16]) -> String {
        var s = "const uint16_t \(name)[2048] = {\n"
        let perLine = 8
        for row in stride(from: 0, to: values.count, by: perLine) {
            s += "    "
            let end = min(row + perLine, values.count)
            for i in row..<end {
                s += String(format: "0x%04X,", values[i])
                if i < end - 1 { s += " " }
            }
            s += "\n"
        }
        s += "};\n"
        return s
    }

    private func dumpUVLCArray(name: String, values: [UVLCEntry]) -> String {
        var s = "const uint32_t \(name)[\(values.count)] = {\n"
        for (i, e) in values.enumerated() {
            let packed: UInt32 =
                UInt32(e.pre & 0xFF)
                | (UInt32(e.preLen & 0xFF) << 8)
                | (UInt32(e.suf & 0xFF)    << 16)
                | (UInt32(e.sufLen & 0xFF) << 24)
            s += String(format: "    0x%08X, // [%2d] pre=%d preLen=%d suf=%d sufLen=%d\n",
                        packed, i, e.pre, e.preLen, e.suf, e.sufLen)
        }
        s += "};\n"
        return s
    }
}
