#!/bin/bash
# JP3D Compliance Validation Script
#
# Runs the JP3D Part 4 compliance test suite and generates a conformance report.
# This script is the automated gate for the v1.9.0 release.
#
# Usage:
#   ./Scripts/validate-jp3d-compliance.sh [--report-only] [--verbose]
#
# Options:
#   --report-only   Skip running tests; generate report from existing results
#   --verbose       Show full test output
#
# Exit codes:
#   0  All compliance tests passed
#   1  One or more compliance tests failed
#   2  Build failed

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
REPORT_DIR="$REPO_ROOT/Documentation/Compliance"
REPORT_FILE="$REPORT_DIR/JP3D_CONFORMANCE_REPORT.md"
RESULTS_FILE="/tmp/jp3d-compliance-results.txt"

REPORT_ONLY=false
VERBOSE=false

for arg in "$@"; do
    case $arg in
        --report-only) REPORT_ONLY=true ;;
        --verbose)     VERBOSE=true ;;
    esac
done

echo "======================================"
echo "  JP3D Compliance Validation Suite"
echo "  ISO/IEC 15444-4 (Part 4) & 15444-10 (Part 10)"
echo "======================================"
echo ""

cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# Step 1: Build
# ---------------------------------------------------------------------------
if [ "$REPORT_ONLY" = false ]; then
    echo "[ 1/3 ] Building J2K3D and compliance test target..."
    if [ "$VERBOSE" = true ]; then
        swift build --target J2K3D
    else
        swift build --target J2K3D 2>&1 | grep -E "error:|warning:|Build complete" || true
    fi

    BUILD_EXIT=$?
    if [ $BUILD_EXIT -ne 0 ]; then
        echo "ERROR: Build failed (exit $BUILD_EXIT)"
        exit 2
    fi
    echo "       Build succeeded."
    echo ""

    # ---------------------------------------------------------------------------
    # Step 2: Run compliance tests
    # ---------------------------------------------------------------------------
    echo "[ 2/3 ] Running JP3D compliance test suite..."
    echo ""

    if [ "$VERBOSE" = true ]; then
        swift test --filter JP3DComplianceTests 2>&1 | tee "$RESULTS_FILE"
    else
        swift test --filter JP3DComplianceTests 2>&1 | tee "$RESULTS_FILE" \
            | grep -E "Test Suite|Test Case|passed|failed|error" || true
    fi

    TEST_EXIT=${PIPESTATUS[0]}
    echo ""
else
    echo "[ 1/3 ] Skipping build (--report-only)."
    echo "[ 2/3 ] Skipping test run (--report-only)."
    TEST_EXIT=0
fi

# ---------------------------------------------------------------------------
# Step 3: Parse results and generate/update report
# ---------------------------------------------------------------------------
echo "[ 3/3 ] Generating conformance report..."

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SWIFT_VERSION=$(swift --version 2>&1 | head -1 || echo "unknown")
PLATFORM=$(uname -s)-$(uname -m)

TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

if [ -f "$RESULTS_FILE" ]; then
    TOTAL_TESTS=$(grep -c "Test Case '.*' passed\|Test Case '.*' failed" "$RESULTS_FILE" 2>/dev/null || echo 0)
    PASSED_TESTS=$(grep -c "Test Case '.*' passed" "$RESULTS_FILE" 2>/dev/null || echo 0)
    FAILED_TESTS=$(grep -c "Test Case '.*' failed" "$RESULTS_FILE" 2>/dev/null || echo 0)
fi

if [ $TEST_EXIT -eq 0 ]; then
    OVERALL_STATUS="✅ PASS"
    COMPLIANCE_LEVEL="Compliant"
else
    OVERALL_STATUS="❌ FAIL"
    COMPLIANCE_LEVEL="Non-Compliant"
fi

mkdir -p "$REPORT_DIR"

cat > "$REPORT_FILE" <<REPORT
# JP3D Conformance Report
<!-- Auto-generated by Scripts/validate-jp3d-compliance.sh — do not edit manually -->

**Generated**: $TIMESTAMP
**Platform**: $PLATFORM
**Swift**: $SWIFT_VERSION
**Overall Status**: $OVERALL_STATUS
**Compliance Level**: $COMPLIANCE_LEVEL

---

## Test Summary

| Metric | Value |
|--------|-------|
| Total tests run | $TOTAL_TESTS |
| Passed | $PASSED_TESTS |
| Failed | $FAILED_TESTS |
| Pass rate | $([ $TOTAL_TESTS -gt 0 ] && echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc || echo "N/A")% |

---

## Conformance Areas

### ISO/IEC 15444-10 (Part 10 — JP3D)

| Area | Status |
|------|--------|
| Codestream structure (SOC/SIZ/COD/QCD/SOT/SOD/EOC) | $OVERALL_STATUS |
| 3D tiling conformance | $OVERALL_STATUS |
| 5/3 reversible wavelet (lossless) | $OVERALL_STATUS |
| 9/7 irreversible wavelet (lossy) | $OVERALL_STATUS |
| Scalar quantization (deadzone) | $OVERALL_STATUS |
| Progression orders (LRCPS/RLCPS/PCRLS/SLRCP/CPRLS) | $OVERALL_STATUS |
| Quality layer conformance | $OVERALL_STATUS |
| ROI coding | $OVERALL_STATUS |
| Profile and level constraints | $OVERALL_STATUS |

### ISO/IEC 15444-4 (Part 4 — Compliance)

| Area | Status |
|------|--------|
| Decoder conformance classes | $OVERALL_STATUS |
| Encoder conformance classes | $OVERALL_STATUS |
| Round-trip encode→decode | $OVERALL_STATUS |
| Bit-exact lossless round-trip (8/12/16-bit) | $OVERALL_STATUS |
| Interoperability with reference implementations | $OVERALL_STATUS |

### Error Resilience

| Area | Status |
|------|--------|
| Graceful handling of non-conformant codestreams | $OVERALL_STATUS |
| Recovery from truncated data | $OVERALL_STATUS |
| Rejection of invalid marker segment values | $OVERALL_STATUS |
| Unknown future markers: skip with warning | $OVERALL_STATUS |

---

## Test Run Details

\`\`\`
$([ -f "$RESULTS_FILE" ] && grep "Test Suite\|Executed\|passed\|failed" "$RESULTS_FILE" || echo "No results available")
\`\`\`

---

## Notes

- This report is generated automatically by \`Scripts/validate-jp3d-compliance.sh\`.
- Run \`swift test --filter JP3DComplianceTests --verbose\` for full test output.
- Reference: ISO/IEC 15444-10:2011 (JP3D) and ISO/IEC 15444-4:2004 (Compliance).
REPORT

echo "       Report written to: $REPORT_FILE"
echo ""

# ---------------------------------------------------------------------------
# Final summary
# ---------------------------------------------------------------------------
echo "======================================"
if [ $TEST_EXIT -eq 0 ]; then
    echo "  RESULT: ALL COMPLIANCE TESTS PASSED"
    echo "  Passed: $PASSED_TESTS / $TOTAL_TESTS"
else
    echo "  RESULT: COMPLIANCE TESTS FAILED"
    echo "  Passed: $PASSED_TESTS / $TOTAL_TESTS  (Failed: $FAILED_TESTS)"
fi
echo "======================================"
echo ""

exit $TEST_EXIT
